- life/_posts/2021-08-30-shopping.md
Add an extended description of some of the main shops, and calls to action for the rest.
> Update Shopping page

- first/_posts/2021-08-10-courses.md
- first/_posts/2021-08-10-projects.md
- first/index.md
- last/_posts/2021-08-30-jury.md
- life/_posts/2021-08-30-apps.md
Please check and let me know what you think !
> Add edits suggested by Marta

- last/_posts/2021-08-30-timeline.md
I tried to add information from the email from Doctoral students’ services. 
Please check if what I added is understandable.
> Add more info about the last stretch.

- life/_posts/2021-08-30-shopping.md
I ordered from them this week and they delivered, so it seems legit :-)
> Add more specialty online shops

- _applying/statement-of-purpose.md
- _applying/why-epfl.md
- _config.yml
- applying.md
- first.md
- index.md
I also simplified the index page and removed its use of EPFL-specific jargon, so that people who want to apply don't get scared :-)
> Add applying section with new SoP guide

- ramp.md
> Add words about target audience

- _includes/head.html
- _life/money-americans.md
- assets/css/style.scss
- index.md
This is quite long and contains a few (relevant) digressions, so happy to take suggestions on shortening it. Also would appreciate proofreading to make sure it is clear and understandable.
> Add page about finances for Americans

- _life/money-americans.md
Everything about finances is always more complicated than it seems.
> Incorporate comments from various people

- _life/money-americans.md
Don't merge until Monday because I may have a couple more things to add before then
> Misc edits, including based on 2022 filing experience

- index.md
Update the current maintainer, sort contributors, add a separate bit for maintainers, and add Deniz who contributed the IC cluster doc.
> Update maintainer & contributors

- _life/money.md
Start with a short version, make the text a bit more concise, and improve the taxes section in particular
> Update money & taxes

- _life/transportation.md
- first.md
> Add info on exchanging foreign driver's licenses

- _life/shopping.md
just got delivered yesterday, can confirm they're real (and useful since as usual most spices/herbs cost waaaaay less in bulk)
my current backlog, in case someone wants to help:
- https://uchitomishop.ch/
- https://dalchini.ch/
- https://www.thungourmet.ch/ (this seems more expensive)
- https://swedishness.ch/
- https://www.osina.ch
- https://www.merlasco.com/
> Add an online shop

- _last/timeline.md
> Addressing a note about September on graduation timeline

- .gitignore
- 404.md
- _config.yml
- _layouts/default.html
- _layouts/guide.html
- _layouts/post.html
- _life/money-americans.md
- _middle/absences.md
- _middle/epfl_infrastructure.md
- _middle/ic_compute_storage.md
- _middle/ic_people_website.md
- applying.md
- assets/css/style.scss
- first.md
- last.md
- life.md
- middle.md
- ramp.md
Best reviewed commit by commit, and entirely described by commit titles.
Fixes #46 (I had forgotten to make that change in my restructuring PR)
> Minor improvements

- _middle/supervising.md
Adding info about:
- summer@EPFL
- SCITAS resources
- difference between master project and thesis project
Coauthored with Martin Everaert!
> Update Project Supervision Guide

- _last/timeline.md
Turns out there's more advisor involvement than I thought
> Update graduation timeline

- _life/hiking.md
- _life/insurance.md
- _life/leisure.md
- _life/money-americans.md
- _life/money.md
- index.md
I shuffled some stuff around to improve the organization and remove some of the redundancy.
> Port Aditya's hiking guide

- _life/shopping.md
Still using this list as my own personal list of online stores :p also I added markets since I was mentioning it in the new item anyway
> Add markets info & an Italian online store to life/shopping

- _life/hiking.md
Updated the hiking doc after the 2024 season.
> Updated Hiking 2024

- _life/shopping.md
Their [website](https://mekongfood.ch/) doesn't provide any useful information (just a bunch of firework animations. If I am wrong, please tell me), so here use their Facebook page.
> Add an Asian store to life/shopping

- _middle/internship.md
@Boyaw @amansouri3476 @SolalPirelli @neo-apz @zhekai-jiang @negar-foroutan
What do you think? Any other concrete steps to propose to people in this situation?
> First draft of explaining Zürich rules
